// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608124441_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscussionId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<string>("ServerFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Application Bug"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Network Issue"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "User Issue"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.Property<int>("DiscussionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscussionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DiscussionId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("Domain.Entities.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"));

                    b.Property<int>("ExpectedDays")
                        .HasColumnType("int");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriorityId");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            PriorityId = 1,
                            ExpectedDays = 14,
                            PriorityName = "Low"
                        },
                        new
                        {
                            PriorityId = 2,
                            ExpectedDays = 7,
                            PriorityName = "Medium"
                        },
                        new
                        {
                            PriorityId = 3,
                            ExpectedDays = 1,
                            PriorityName = "High"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Product 1"
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Product 2"
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Product 3"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<string>("AssignedToId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RaisedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RaisedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RaisedBy");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            CategoryId = 1,
                            Description = "Description for ticket 1",
                            ExpectedDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "NEW",
                            Summary = "Sample ticket 1"
                        },
                        new
                        {
                            TicketId = 2,
                            CategoryId = 2,
                            Description = "Description for ticket 2",
                            ExpectedDate = new DateTime(2024, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OPEN",
                            Summary = "Sample ticket 2"
                        },
                        new
                        {
                            TicketId = 3,
                            CategoryId = 1,
                            Description = "Description for ticket 3",
                            ExpectedDate = new DateTime(2024, 9, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "NEW",
                            Summary = "Sample ticket 3"
                        },
                        new
                        {
                            TicketId = 4,
                            CategoryId = 2,
                            Description = "Description for ticket 4",
                            ExpectedDate = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OPEN",
                            Summary = "Sample ticket 4"
                        },
                        new
                        {
                            TicketId = 5,
                            CategoryId = 3,
                            Description = "Description for ticket 5",
                            ExpectedDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 5"
                        },
                        new
                        {
                            TicketId = 6,
                            CategoryId = 1,
                            Description = "Description for ticket 6",
                            ExpectedDate = new DateTime(2024, 9, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "NEW",
                            Summary = "Sample ticket 6"
                        },
                        new
                        {
                            TicketId = 7,
                            CategoryId = 2,
                            Description = "Description for ticket 7",
                            ExpectedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OPEN",
                            Summary = "Sample ticket 7"
                        },
                        new
                        {
                            TicketId = 8,
                            CategoryId = 3,
                            Description = "Description for ticket 8",
                            ExpectedDate = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 8"
                        },
                        new
                        {
                            TicketId = 9,
                            CategoryId = 1,
                            Description = "Description for ticket 9",
                            ExpectedDate = new DateTime(2024, 3, 9, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "NEW",
                            Summary = "Sample ticket 9"
                        },
                        new
                        {
                            TicketId = 10,
                            CategoryId = 2,
                            Description = "Description for ticket 10",
                            ExpectedDate = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OPEN",
                            Summary = "Sample ticket 10"
                        },
                        new
                        {
                            TicketId = 11,
                            CategoryId = 3,
                            Description = "Description for ticket 11",
                            ExpectedDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 11"
                        },
                        new
                        {
                            TicketId = 12,
                            CategoryId = 1,
                            Description = "Description for ticket 12",
                            ExpectedDate = new DateTime(2024, 6, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "NEW",
                            Summary = "Sample ticket 12"
                        },
                        new
                        {
                            TicketId = 13,
                            CategoryId = 2,
                            Description = "Description for ticket 13",
                            ExpectedDate = new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OPEN",
                            Summary = "Sample ticket 13"
                        },
                        new
                        {
                            TicketId = 14,
                            CategoryId = 3,
                            Description = "Description for ticket 14",
                            ExpectedDate = new DateTime(2024, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 14"
                        },
                        new
                        {
                            TicketId = 15,
                            CategoryId = 1,
                            Description = "Description for ticket 15",
                            ExpectedDate = new DateTime(2024, 9, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "NEW",
                            Summary = "Sample ticket 15"
                        },
                        new
                        {
                            TicketId = 16,
                            CategoryId = 2,
                            Description = "Description for ticket 16",
                            ExpectedDate = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OPEN",
                            Summary = "Sample ticket 16"
                        },
                        new
                        {
                            TicketId = 17,
                            CategoryId = 3,
                            Description = "Description for ticket 17",
                            ExpectedDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 17"
                        },
                        new
                        {
                            TicketId = 18,
                            CategoryId = 1,
                            Description = "Description for ticket 18",
                            ExpectedDate = new DateTime(2024, 3, 18, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "NEW",
                            Summary = "Sample ticket 18"
                        },
                        new
                        {
                            TicketId = 19,
                            CategoryId = 2,
                            Description = "Description for ticket 19",
                            ExpectedDate = new DateTime(2024, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OPEN",
                            Summary = "Sample ticket 19"
                        },
                        new
                        {
                            TicketId = 20,
                            CategoryId = 3,
                            Description = "Description for ticket 20",
                            ExpectedDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 20"
                        },
                        new
                        {
                            TicketId = 21,
                            CategoryId = 2,
                            Description = "Description for ticket 21",
                            ExpectedDate = new DateTime(2024, 6, 10, 7, 40, 49, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 6, 5, 7, 40, 49, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 21"
                        },
                        new
                        {
                            TicketId = 22,
                            CategoryId = 2,
                            Description = "Description for ticket 22",
                            ExpectedDate = new DateTime(2023, 11, 6, 23, 56, 10, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 11, 6, 15, 56, 10, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 22"
                        },
                        new
                        {
                            TicketId = 23,
                            CategoryId = 3,
                            Description = "Description for ticket 23",
                            ExpectedDate = new DateTime(2023, 10, 9, 16, 10, 57, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 10, 1, 16, 10, 57, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 23"
                        },
                        new
                        {
                            TicketId = 24,
                            CategoryId = 2,
                            Description = "Description for ticket 24",
                            ExpectedDate = new DateTime(2023, 10, 24, 3, 16, 57, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 10, 23, 19, 16, 57, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 24"
                        },
                        new
                        {
                            TicketId = 25,
                            CategoryId = 1,
                            Description = "Description for ticket 25",
                            ExpectedDate = new DateTime(2023, 11, 27, 4, 18, 47, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 11, 22, 4, 18, 47, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 25"
                        },
                        new
                        {
                            TicketId = 26,
                            CategoryId = 1,
                            Description = "Description for ticket 26",
                            ExpectedDate = new DateTime(2024, 6, 7, 0, 28, 17, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 5, 30, 0, 28, 17, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 26"
                        },
                        new
                        {
                            TicketId = 27,
                            CategoryId = 2,
                            Description = "Description for ticket 27",
                            ExpectedDate = new DateTime(2024, 5, 10, 20, 13, 4, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 5, 2, 20, 13, 4, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 27"
                        },
                        new
                        {
                            TicketId = 28,
                            CategoryId = 3,
                            Description = "Description for ticket 28",
                            ExpectedDate = new DateTime(2024, 7, 28, 21, 1, 34, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 7, 28, 13, 1, 34, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 28"
                        },
                        new
                        {
                            TicketId = 29,
                            CategoryId = 2,
                            Description = "Description for ticket 29",
                            ExpectedDate = new DateTime(2023, 10, 6, 9, 3, 20, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 10, 1, 9, 3, 20, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 29"
                        },
                        new
                        {
                            TicketId = 30,
                            CategoryId = 2,
                            Description = "Description for ticket 30",
                            ExpectedDate = new DateTime(2024, 4, 26, 18, 56, 12, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 4, 21, 18, 56, 12, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 30"
                        },
                        new
                        {
                            TicketId = 31,
                            CategoryId = 2,
                            Description = "Description for ticket 31",
                            ExpectedDate = new DateTime(2023, 12, 5, 11, 40, 49, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 12, 5, 3, 40, 49, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 31"
                        },
                        new
                        {
                            TicketId = 32,
                            CategoryId = 1,
                            Description = "Description for ticket 32",
                            ExpectedDate = new DateTime(2023, 8, 15, 12, 50, 18, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 8, 10, 12, 50, 18, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 32"
                        },
                        new
                        {
                            TicketId = 33,
                            CategoryId = 3,
                            Description = "Description for ticket 33",
                            ExpectedDate = new DateTime(2023, 8, 6, 5, 16, 30, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 7, 29, 5, 16, 30, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 33"
                        },
                        new
                        {
                            TicketId = 34,
                            CategoryId = 1,
                            Description = "Description for ticket 34",
                            ExpectedDate = new DateTime(2023, 12, 25, 14, 40, 25, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 12, 25, 6, 40, 25, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 34"
                        },
                        new
                        {
                            TicketId = 35,
                            CategoryId = 2,
                            Description = "Description for ticket 35",
                            ExpectedDate = new DateTime(2023, 8, 7, 11, 10, 42, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 7, 30, 11, 10, 42, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 35"
                        },
                        new
                        {
                            TicketId = 36,
                            CategoryId = 3,
                            Description = "Description for ticket 36",
                            ExpectedDate = new DateTime(2024, 1, 1, 4, 36, 12, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 12, 31, 20, 36, 12, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 36"
                        },
                        new
                        {
                            TicketId = 37,
                            CategoryId = 1,
                            Description = "Description for ticket 37",
                            ExpectedDate = new DateTime(2023, 9, 6, 12, 11, 15, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 9, 1, 12, 11, 15, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 37"
                        },
                        new
                        {
                            TicketId = 38,
                            CategoryId = 2,
                            Description = "Description for ticket 38",
                            ExpectedDate = new DateTime(2023, 10, 20, 10, 43, 29, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 10, 12, 10, 43, 29, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 38"
                        },
                        new
                        {
                            TicketId = 39,
                            CategoryId = 3,
                            Description = "Description for ticket 39",
                            ExpectedDate = new DateTime(2024, 7, 20, 8, 50, 11, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 7, 15, 8, 50, 11, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 39"
                        },
                        new
                        {
                            TicketId = 40,
                            CategoryId = 2,
                            Description = "Description for ticket 40",
                            ExpectedDate = new DateTime(2024, 4, 22, 17, 28, 30, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 4, 22, 9, 28, 30, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 40"
                        },
                        new
                        {
                            TicketId = 41,
                            CategoryId = 1,
                            Description = "Description for ticket 41",
                            ExpectedDate = new DateTime(2023, 9, 22, 14, 15, 30, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 9, 14, 14, 15, 30, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 41"
                        },
                        new
                        {
                            TicketId = 42,
                            CategoryId = 3,
                            Description = "Description for ticket 42",
                            ExpectedDate = new DateTime(2023, 12, 8, 11, 23, 18, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 12, 3, 11, 23, 18, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 42"
                        },
                        new
                        {
                            TicketId = 43,
                            CategoryId = 2,
                            Description = "Description for ticket 43",
                            ExpectedDate = new DateTime(2023, 10, 27, 22, 19, 44, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 10, 22, 16, 19, 44, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 43"
                        },
                        new
                        {
                            TicketId = 44,
                            CategoryId = 1,
                            Description = "Description for ticket 44",
                            ExpectedDate = new DateTime(2023, 11, 15, 9, 7, 55, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 11, 7, 9, 7, 55, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 44"
                        },
                        new
                        {
                            TicketId = 45,
                            CategoryId = 2,
                            Description = "Description for ticket 45",
                            ExpectedDate = new DateTime(2023, 7, 23, 12, 41, 29, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 7, 18, 12, 41, 29, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 45"
                        },
                        new
                        {
                            TicketId = 46,
                            CategoryId = 3,
                            Description = "Description for ticket 46",
                            ExpectedDate = new DateTime(2023, 9, 5, 18, 56, 11, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 9, 5, 10, 56, 11, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 46"
                        },
                        new
                        {
                            TicketId = 47,
                            CategoryId = 1,
                            Description = "Description for ticket 47",
                            ExpectedDate = new DateTime(2024, 4, 22, 13, 13, 30, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 4, 14, 13, 13, 30, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 47"
                        },
                        new
                        {
                            TicketId = 48,
                            CategoryId = 3,
                            Description = "Description for ticket 48",
                            ExpectedDate = new DateTime(2024, 2, 13, 17, 12, 15, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 2, 8, 17, 12, 15, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 48"
                        },
                        new
                        {
                            TicketId = 49,
                            CategoryId = 2,
                            Description = "Description for ticket 49",
                            ExpectedDate = new DateTime(2024, 3, 16, 15, 45, 48, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 3, 16, 7, 45, 48, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 49"
                        },
                        new
                        {
                            TicketId = 50,
                            CategoryId = 1,
                            Description = "Description for ticket 50",
                            ExpectedDate = new DateTime(2023, 12, 3, 16, 19, 33, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 11, 25, 16, 19, 33, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 50"
                        },
                        new
                        {
                            TicketId = 51,
                            CategoryId = 3,
                            Description = "Description for ticket 51",
                            ExpectedDate = new DateTime(2023, 10, 9, 15, 26, 21, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 10, 1, 15, 26, 21, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 51"
                        },
                        new
                        {
                            TicketId = 52,
                            CategoryId = 2,
                            Description = "Description for ticket 52",
                            ExpectedDate = new DateTime(2023, 10, 4, 8, 30, 17, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 9, 29, 8, 30, 17, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 52"
                        },
                        new
                        {
                            TicketId = 53,
                            CategoryId = 3,
                            Description = "Description for ticket 53",
                            ExpectedDate = new DateTime(2024, 1, 13, 22, 36, 48, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 1, 13, 14, 36, 48, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 53"
                        },
                        new
                        {
                            TicketId = 54,
                            CategoryId = 1,
                            Description = "Description for ticket 54",
                            ExpectedDate = new DateTime(2023, 8, 26, 10, 17, 29, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 8, 21, 10, 17, 29, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 54"
                        },
                        new
                        {
                            TicketId = 55,
                            CategoryId = 3,
                            Description = "Description for ticket 55",
                            ExpectedDate = new DateTime(2024, 5, 20, 13, 59, 36, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 5, 20, 5, 59, 36, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 55"
                        },
                        new
                        {
                            TicketId = 56,
                            CategoryId = 2,
                            Description = "Description for ticket 56",
                            ExpectedDate = new DateTime(2023, 11, 27, 16, 23, 9, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 11, 19, 16, 23, 9, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 56"
                        },
                        new
                        {
                            TicketId = 57,
                            CategoryId = 1,
                            Description = "Description for ticket 57",
                            ExpectedDate = new DateTime(2023, 8, 15, 9, 40, 13, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 8, 10, 9, 40, 13, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 57"
                        },
                        new
                        {
                            TicketId = 58,
                            CategoryId = 3,
                            Description = "Description for ticket 58",
                            ExpectedDate = new DateTime(2023, 11, 7, 11, 7, 25, 0, DateTimeKind.Unspecified),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 10, 30, 11, 7, 25, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 58"
                        },
                        new
                        {
                            TicketId = 59,
                            CategoryId = 2,
                            Description = "Description for ticket 59",
                            ExpectedDate = new DateTime(2024, 6, 15, 20, 19, 44, 0, DateTimeKind.Unspecified),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2024, 6, 15, 12, 19, 44, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 59"
                        },
                        new
                        {
                            TicketId = 60,
                            CategoryId = 1,
                            Description = "Description for ticket 60",
                            ExpectedDate = new DateTime(2023, 9, 7, 18, 24, 59, 0, DateTimeKind.Unspecified),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            RaisedDate = new DateTime(2023, 9, 2, 18, 24, 59, 0, DateTimeKind.Unspecified),
                            Status = "CLOSED",
                            Summary = "Sample ticket 60"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AccountConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "62f94fe7-0580-42df-969c-50d4165d63b9",
                            AccessFailedCount = 0,
                            AccountConfirmed = false,
                            ConcurrencyStamp = "5a5204f6-486e-4ade-b493-61326e6993d3",
                            Email = "Test@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@GMAIL.COM",
                            NormalizedUserName = "TEST@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJHFh4+6htwL7Vgoo/aKC4yQBnj9tWPX+sYLAY5KxQfqHWVg1EN/M2cANAEhw9FD7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b340117d-16b4-4a64-8415-435db3a93dd1",
                            TwoFactorEnabled = false,
                            UserName = "Test@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Domain.Entities.Discussion", "Discussion")
                        .WithMany("Attachments")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId");

                    b.Navigation("Discussion");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("Priority");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
